# Generated by Django 3.2.16 on 2022-11-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='remark',
        ),
    ]
