# Generated by Django 3.2.16 on 2022-11-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0003_auto_20221129_1426'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='TenderImport',
        ),
    ]
