# Generated by Django 3.2.16 on 2022-11-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0004_rename_file_tenderimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tenderimport',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='file_images'),
        ),
    ]
