# Generated by Django 3.2.16 on 2022-12-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0006_alter_tenderimport_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderimport',
            name='CustomerRefNo',
            field=models.CharField(max_length=50),
        ),
    ]
