# Generated by Django 3.2.16 on 2022-12-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0007_alter_tenderimport_customerrefno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderimport',
            name='CustomerRefNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
