# Generated by Django 3.2.16 on 2022-12-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0009_alter_tenderimport_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderimport',
            name='Image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
